services:
  localstack:
    image: localstack/localstack:4.4.0
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEFAULT_REGION: us-east-1
    volumes:
      - localstack-data:/var/lib/localstack
      
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Puerto de comunicación AMQP
      - "15672:15672" # Puerto de la interfaz web de administración
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}

  enrollment-platform:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-local}/enrollment-platform:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      ORACLE_WALLET_DIR: /app/wallet
      TNS_ADMIN: /app/wallet
    volumes:
      - ${ORACLE_WALLET_DIR:-./Wallet_ENROLLMENTPLATFORMDB}:/app/wallet:ro
    restart: always
    depends_on:
      - localstack
      - rabbitmq
volumes:
  localstack-data:
