spring.application.name=EnrollmentPlatform
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
management.endpoints.web.exposure.include=health

# ==========================================
# CONFIGURACION DE RABBITMQ
# ==========================================
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}